
type RequiredEnv =
  | "NEXT_PUBLIC_FIREBASE_API_KEY"
  | "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
  | "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
  | "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
  | "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
  | "NEXT_PUBLIC_FIREBASE_APP_ID"
  // THÊM BIẾN RECAPTCHA VÀO ĐỂ ĐỌC
  | "NEXT_PUBLIC_RECAPTCHA_SITE_KEY";

function readEnv<K extends RequiredEnv>(key: K): string {
  const val = process.env[key];
  if (!val || val.trim() === "") {
    throw new Error(`Thiếu biến môi trường ${key}. Kiểm tra .env.local / secrets.`);
  }
  return val;
}

export const env = {
  NEXT_PUBLIC_FIREBASE_API_KEY: readEnv("NEXT_PUBLIC_FIREBASE_API_KEY"),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: readEnv("NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: readEnv("NEXT_PUBLIC_FIREBASE_PROJECT_ID"),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: readEnv("NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: readEnv("NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"),
  NEXT_PUBLIC_FIREBASE_APP_ID: readEnv("NEXT_PUBLIC_FIREBASE_APP_ID"),
  // THÊM BIẾN RECAPTCHA VÀO ĐỂ EXPORT
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: readEnv("NEXT_PUBLIC_RECAPTCHA_SITE_KEY"),
};
